Feature/sec os 11s
tiiuae/mesh_com pull request #132
Opened 2022-03-07 12:12 UTC by govindsi

2022-03-08 05:14 UTC, martin-tii approved these changes

2022-03-15 09:16 UTC, joenpera requested changes

2022-03-15 09:16 UTC, joenpera commented on common/scripts/mesh-11s.sh
> +iw dev "$wifidev" set mesh_param mesh_fwding 1
Should be:
iw dev "$wifidev" set mesh_param mesh_fwding 0

2022-03-15 10:57 UTC, joenpera commented on common/scripts/mesh-11s.sh
> +iw dev "$wifidev" set mesh_param mesh_fwding 1
fixed with [55e2be6](https://github.com/tiiuae/mesh_com/pull/132/commits/55e2be66d7497aa10eca90288344f5ef7da7db9e)

2022-03-15 13:50 UTC, joenpera approved these changes

2022-03-15 14:18 UTC, merged