Fix ament_flake8 and ament_pep257 errors
tiiuae/mesh_com pull request #144
Opened 2022-04-05 09:44 UTC by saauvine

* Cosmetic changes to comply with pep8/pep257 rules.
* Control.em deleted.

Signed-off-by: Saku Auvinen <saku.auvinen@unikie.com>

2022-04-19 11:11 UTC, joenpera approved these changes

2022-04-19 12:41 UTC, liljaj approved these changes

2022-06-10 12:11 UTC, joenpera requested changes
blocked until tested with cpu load fix

2023-03-13 09:42 UTC, saauvine commented
Closing this as PR itself is obsolete. Will do changes later via other PR.

2023-03-13 09:42 UTC, closed without merging