qos version
tiiuae/mesh_com pull request #249
Opened 2023-03-14 10:58 UTC by francislin12

Qos_version_2

2023-03-14 11:08 UTC, mbaddeley commented
Hi Francis, please confirm that all regression testing has been performed. I.e., with these changes does BATMAN work in the following configurations:

1. Laptop -> Eth -> Node -> BATMAN -> Node-> Eth -> Laptop
2. Laptop/Phone -> MCC AP -> Node -> BATMAN -> Node -> MCC AP -> Laptop/Phone
3. Laptop/Phone -> SCC AP -> Node -> BATMAN -> Node -> SCC AP -> Laptop/Phone

And then the same for QoS-OLSR:

4. Laptop -> Eth -> Node -> QoS-OLSR -> Node-> Eth -> Laptop
5. Laptop/Phone -> MCC AP -> Node -> QoS-OLSR -> Node -> MCC AP -> Laptop/Phone
6. Laptop/Phone -> SCC AP -> Node -> QoS-OLSR -> Node -> SCC AP -> Laptop/Phone

For the MCC/SCC modes it would be ok to use either Phone or Laptop.

2023-03-14 11:13 UTC, mbaddeley requested changes
Please convert all whitespace to the original format (x2 SPACES instead of x1 TAB) as this will make the merge a lot easier to read. Currently it is showing changes in almost every line because you have changed the whitespace format.

Here is how to change the vscode settings to show whitespace: https://stackoverflow.com/questions/30140595/show-whitespace-characters-in-visual-studio-code

Here is how to convert all the TABS back to spaces (make sure it converts to x2 spaces): https://stackoverflow.com/questions/33974681/how-can-i-convert-tabs-to-spaces-and-vice-versa-in-an-existing-file

2023-03-14 11:48 UTC, joenpera requested changes
Why platform detection was removed?  It is needed for correct ethernet port setup and it it different between hardwares.

2023-03-22 11:18 UTC, mbaddeley commented on modules/utils/docker/entrypoint.sh
> +#! /bin/bash -x
remove -x

2023-03-22 11:19 UTC, mbaddeley commented on modules/utils/docker/entrypoint.sh
> +  source /opt/mesh.conf
correct whitespace

2023-03-22 11:19 UTC, mbaddeley commented on modules/utils/docker/entrypoint.sh
> +  killall hostapd
correct whitespace

2023-03-22 11:23 UTC, mbaddeley commented on modules/utils/docker/entrypoint.sh
> +create_ap_config()
Pretty sure this function is no longer used? @joenpera?

2023-03-22 11:24 UTC, mbaddeley commented on modules/utils/docker/entrypoint.sh
> +create_ap_config()
Moved to a new place unecessarily. If you look at the original file it was originally down below.

2023-03-22 11:25 UTC, mbaddeley commented on modules/utils/docker/entrypoint.sh
> +  ifname_ap="$(ifconfig -a | grep -E '^wlan' -m 1 | awk -F':' '{ print $1 }')"
Unecessary change from develop

2023-03-22 11:25 UTC, mbaddeley commented on modules/utils/docker/entrypoint.sh
> +    brctl addif br-lan "$mesh_if" "$ifname_ap"
Fix whitespace

2023-03-22 11:45 UTC, joenpera commented on modules/utils/docker/entrypoint.sh
> +    ieee80211n=0
disable ieee80211n?

2023-08-29 07:12 UTC, closed without merging