Mesh Shield 1.5 integrated on develop
tiiuae/mesh_com pull request #255
Opened 2023-03-17 07:36 UTC by martin-tii

This PR is to merge MS 1.5 on develop branch.
Still has compatibility with MS 1.0.

2023-03-17 07:50 UTC, DamienDeMayaTII commented
I cannot approve / reject but it is ok since only 2 are needed and let's use the technical people for that. As discussed with Martin, in the future we should have PRs to Dev/Mainstream at least once a month. That requires that upcoming features for Q2 onwards has better DoD and divided into small deliverables / sub features. Finally, commits should be linked to Jira as much as possible and vice-versa. Please @govindsi, @mbaddeley, @martin-tii, help me to spread the message among your teams. Thanks!

2023-03-17 08:26 UTC, joenpera commented
General comment: please use Python PEP8 and ShellCheck for shell scripts.   Lot of complains comes out of those tools and quite often those are also possible bugs.

2023-03-17 10:28 UTC, joenpera requested changes
Lot of unused imports and variables.  Please use PEP8 and shellcheck for code styling and static analysis.

2023-03-17 10:28 UTC, joenpera commented on modules/sc-mesh-secure-deployment/src/1_5/common/ConnectionMgr.py
> +        subprocess.call(com, shell=False)
com - might be used before assignment

2023-03-17 10:28 UTC, joenpera commented on modules/sc-mesh-secure-deployment/src/1_5/common/ConnectionMgr.py
> +        mesh_mac = self.util.get_mac_by_interface(mesh_vif)
mesh_vif - possible use before assignment

2023-03-17 10:28 UTC, joenpera commented on modules/sc-mesh-secure-deployment/src/1_5/compiled_krb/ness_check_bc.py
2 spaces indent vs 4 spaces.

2023-03-17 10:28 UTC, joenpera commented on modules/sc-mesh-secure-deployment/src/1_5/features/continuous/ca_main.py
> +        flag_ctr = 0
newer used

2023-03-17 10:28 UTC, joenpera commented on modules/sc-mesh-secure-deployment/src/1_5/features/mba/mba.py
> +import sys
Not used imports

2023-03-22 10:40 UTC, martin-tii commented on modules/sc-mesh-secure-deployment/src/1_5/common/ConnectionMgr.py
> +        subprocess.call(com, shell=False)
Done

2023-03-22 10:40 UTC, martin-tii commented on modules/sc-mesh-secure-deployment/src/1_5/common/ConnectionMgr.py
> +        mesh_mac = self.util.get_mac_by_interface(mesh_vif)
done

2023-03-22 10:41 UTC, martin-tii commented on modules/sc-mesh-secure-deployment/src/1_5/compiled_krb/ness_check_bc.py
This is an autogenerated file, we cannot modify it.
We are currently adding this as future work, because we need to modify the entire logic + tool for decision engine

2023-03-22 10:41 UTC, martin-tii commented on modules/sc-mesh-secure-deployment/src/1_5/features/continuous/ca_main.py
> +        flag_ctr = 0
done

2023-03-22 10:41 UTC, martin-tii commented on modules/sc-mesh-secure-deployment/src/1_5/features/mba/mba.py
> +import sys
done

2023-03-22 10:42 UTC, martin-tii commented
Thanks for your comments. 
All the files (on MS1.5) were shellchecked. Same with the PEP8 for python files. 
https://github.com/tiiuae/mesh_com/pull/255/commits/7cf9af677197b43d9373622a1e57be7e5e3b3eb4

2023-03-22 11:38 UTC, joenpera approved these changes

2023-03-23 04:57 UTC, govindsi approved these changes

2023-03-23 05:04 UTC, merged