Mesh com 1.5 compatibility
tiiuae/mesh_com pull request #268
Opened 2023-04-03 12:15 UTC by SelinaTII

** mesh.conf --> Added BRIDGE=true to enable bridging mode (put false to disable bridge)
** mesh_com_11s.conf --> Added bridge, meshint to denote bridging mode and mesh interface
** entrypoint.sh --> Added condition: if BRIDGE = true in mesh.conf, write bridge: True, meshint: br-lan to mesh_com_11s.conf, else write bridge: False, meshint: bat0
** ConnectionMgr.py: Added attribute bridge to class ConnectionMgr which is read from mesh_com_11s.conf. In starting_mesh(), run bridge_settings() after starting mesh if bridge is true
** mesh_utils.py --> Imported yaml, added function get_mesh_int() to get the interface from meshint in mesh_com_11s.conf, assigned the value returned by get_mesh_int() as default mesh interface in arguments to other functions
** header.py --> Replaced hardcoded value of MESHINT with mesh_utils.get_mesh_int()
** continuous/utils.py --> Replaced hardcoded value of MESHINT with mesh_utils.get_mesh_int()
** continuous/ca_main.py --> Replaced hardcoded value of MESHINT with mesh_utils.get_mesh_int()
** quarantine.py --> Replaced hardcoded interface 'bat0' with mesh_utils.get_mesh_int()
** mutual.py --> Updated my_ip_mesh to be the br-lan ip after the bridge is established

Jira_Id : MSS20-125

Signed-off-by: Selina Shrestha <selina.shrestha@tii.ae>

2023-04-05 07:04 UTC, martin-tii approved these changes

2023-04-07 07:05 UTC, govindsi commented on modules/utils/docker/mesh.conf
config is sourced from /opt/mesh.conf in entrypoint.
source /opt/mesh.conf

We will have to use single config for both 1.0/1.5 version. Probably we can use new config for all modes.

2023-04-07 09:05 UTC, martin-tii requested changes

2023-04-07 10:35 UTC, SelinaTII commented on modules/utils/docker/entrypoint.sh
> +      bridge=$BRIDGE
@govindsi  @martin-tii  I've changed it to get bridge mode from /opt/mesh.conf now

2023-04-17 07:17 UTC, Monika-Research approved these changes
Tested eth mode and it works fine. MCC mode needs to be enabled as well and entrypoint.sh needs to re-structured accordingly. However, it can be a new request.

2023-04-17 07:26 UTC, martin-tii commented
DO NOT MERGE, 
This PR will be closed. 
Use https://github.com/tiiuae/mesh_com/pull/273 instead

2023-04-24 05:33 UTC, martin-tii commented
Replaced with [PR 273](https://github.com/tiiuae/mesh_com/pull/273 )

2023-04-24 05:33 UTC, closed without merging