CherryPicked commits to enable upgrade to latest base image
tiiuae/mesh_com pull request #271
Opened 2023-04-06 09:55 UTC by aravindraja93

PR to solve this issue : https://github.com/tiiuae/mesh_com/issues/270

2023-04-06 11:47 UTC, maseabunikie commented on modules/mesh_com/entrypoint.sh
@joenpera @govindsi 
Please, take a look to this file carefully. This is taken from mesh chain changes done last year. It is possible that you don't want this on the main branch.

2023-04-06 11:53 UTC, joenpera commented on modules/mesh_com/entrypoint.sh
This needs to be asked from @sergei-petroff.  He knows the setup which should be supported in mainline.

2023-04-06 13:30 UTC, joenpera approved these changes

2023-04-06 18:08 UTC, govindsi approved these changes

2023-04-06 18:11 UTC, govindsi reviewed
Seems workflow is still failing.

 cp: cannot stat 'modules/*.deb': No such file or directory
Error: Process completed with exit code 1.

2023-04-06 18:12 UTC, govindsi requested changes
Seems its still require some more changes to fix the workflow.

 cp: cannot stat 'modules/*.deb': No such file or directory
Error: Process completed with exit code 1.

2023-04-07 06:51 UTC, aravindraja93 commented
@govindsi : Debian build script updated. 

And also the deb workflow is repeating having alternate scripts for the same goal , 

These two different scripts are used for the same goal, Better to fix using the same one:

1. https://github.com/tiiuae/mesh_com/blob/main/modules/mesh_com/package.sh
2. https://github.com/tiiuae/fog-ros-baseimage/blob/main/builder/packaging/package.sh

2023-04-07 06:54 UTC, govindsi approved these changes
Looks good now.

2023-04-07 06:57 UTC, merged