Test/dev
tiiuae/mesh_com pull request #34
Opened 2021-06-02 14:26 UTC by govindsi

This series has some minor enhancements.

1) Move certificates to system keystore.
2) Interop issues with raspbian/Linux distro.
3) Allow mesh config with single radio config for non portal mesh point.

2021-06-03 08:32 UTC, mbaddeley approved these changes

2021-06-06 05:37 UTC, mbaddeley commented
Minor Comment: In future can we please stick to hotfix/xxxx or feature/xxxx for PR naming conventions.

2021-06-06 05:48 UTC, martin-tii requested changes
Please, remove the modification on Line 32.
Thanks

2021-06-06 07:37 UTC, govindsi commented on modules/sc-mesh-secure-deployment/src/client-mesh.py
> +        if 'Ubuntu' in aux or 'Raspbian' in aux or 'Linux' in aux:
Ok, got it.
Agreed.

2021-06-09 05:49 UTC, merged