UnitTests and Coverage reporting
tiiuae/mesh_com pull request #444
Opened 2024-04-25 08:36 UTC by joenpera

Jira-Id: SECO-4966

2024-05-13 15:15 UTC, pentestiing requested changes
Plz also check the `mesh_status` :page_with_curl:

2024-05-13 15:15 UTC, pentestiing commented on modules/sc-mesh-secure-deployment/src/nats/tests/test_settings.py
There are many tests here that check `self.assertEqual(ret, "FAIL", msg=f"ret: {ret}, mesh_status: {mesh_status}")` where `ret` and `mesh_status` come directly from the method that's being tested. While I think it's perfectly fine to use this to test the `FAIL` or `OK` status, I believe that in this case the content of the `mesh_status` message shall also be checked against a expected string :upside_down_face:

2024-05-14 05:19 UTC, joenpera commented on modules/sc-mesh-secure-deployment/src/nats/src/comms_command.py
🏳️

2024-05-14 05:36 UTC, joenpera commented on modules/sc-mesh-secure-deployment/src/nats/src/comms_settings.py
> +        except ValueError:
I thought that it was prettier and easier to read.     I will fix all validations to check index and I remove the try/except.

2024-05-14 05:37 UTC, joenpera commented on modules/sc-mesh-secure-deployment/src/nats/src/comms_settings.py
> +        except ValueError:
same as 🔝

2024-05-14 05:37 UTC, joenpera commented on modules/sc-mesh-secure-deployment/src/nats/src/comms_settings.py
> +        except ValueError:
same as 🔝🔝

2024-05-14 05:43 UTC, joenpera commented on modules/sc-mesh-secure-deployment/src/nats/src/comms_command.py
[8c633fd](https://github.com/tiiuae/mesh_com/pull/444/commits/8c633fdc9a11f6873d5e258c3e7107a082615e72)

2024-05-14 05:44 UTC, joenpera commented on modules/sc-mesh-secure-deployment/src/nats/src/comms_settings.py
> +        except ValueError:
[8c633fd](https://github.com/tiiuae/mesh_com/pull/444/commits/8c633fdc9a11f6873d5e258c3e7107a082615e72)

2024-05-14 05:44 UTC, joenpera commented on modules/sc-mesh-secure-deployment/src/nats/src/comms_settings.py
> +        except ValueError:
[8c633fd](https://github.com/tiiuae/mesh_com/pull/444/commits/8c633fdc9a11f6873d5e258c3e7107a082615e72)

2024-05-14 05:44 UTC, joenpera commented on modules/sc-mesh-secure-deployment/src/nats/src/comms_settings.py
> +        except ValueError:
[8c633fd](https://github.com/tiiuae/mesh_com/pull/444/commits/8c633fdc9a11f6873d5e258c3e7107a082615e72)

2024-05-14 05:55 UTC, pentestiing commented on modules/sc-mesh-secure-deployment/src/nats/src/comms_settings.py
> +        except ValueError:
I won't say I'm against this usage of exceptions for accessing arrays by index (I use it myself), but I don't like the double `return <code>, <msg>` duplication as one might think there are differences between the `return` from inside the `if` and the one in the `except`, when in this case there aren't :waffle:

2024-05-14 06:00 UTC, joenpera commented on modules/sc-mesh-secure-deployment/src/nats/src/comms_settings.py
> +        except ValueError:
got your point.

2024-05-15 12:49 UTC, joenpera commented on modules/sc-mesh-secure-deployment/src/nats/tests/test_settings.py
[459af25](https://github.com/tiiuae/mesh_com/pull/444/commits/459af2525362c220e8dd675e7db24741c760d71f)

2024-05-15 14:34 UTC, pentestiing approved these changes
Great party! :tada:

2024-05-17 06:36 UTC, saauvine approved these changes

2024-05-17 08:15 UTC, merged